### PR TITLE
update poi build yaml

### PR DESCRIPTION
**Pull request by dkirby-ms**
Updated build to fix syntax errors

### CODE REVIEW

**Review by jostrandig — APPROVED** [review]

**Review by javieriroman — COMMENTED** [review]
i approved

**Review by jostrandig — CHANGES_REQUESTED** [review]
Bad code

**Comment by dkirby-ms** [comment]
fixed bad code by updating build to use .sln instead of .csproj

**Comment by dkirby-ms** [comment]
Solved build quandary and updated build file. Please re-review

**Review by ahjcloud — APPROVED** [review]
Reviewed and Approved.

**Review by jostrandig — APPROVED** [review]

**Review by javieriroman — APPROVED** [review]

**Pull request merged**
